Emoji reacts
oxen-io/session-ios pull request #638
Opened 2022-06-17 04:26 UTC by RyanRory

2022-08-11 00:07 UTC, mpretty-cyro requested changes

2022-08-11 01:32 UTC, RyanRory commented on SessionMessagingKit/Messages/Message.swift
> +                    let reaction = Reaction(
FYI `.suffix(from: 1)` actually throws...

2022-08-11 01:33 UTC, RyanRory commented on SessionMessagingKit/Open Groups/OpenGroupAPI.swift
> +                    queryParameters: [.reactions : "r"]
Yep, added.

2022-08-11 01:33 UTC, RyanRory commented on SessionMessagingKit/Open Groups/Models/SOGSMessage.swift
> +            posted: ((try? container.decode(TimeInterval.self, forKey: .posted)) ?? Date().timeIntervalSince1970), // Reaction updates don't include posted
Yep, changed the `posted` to be optional.

2022-08-11 01:33 UTC, RyanRory commented on SessionMessagingKit/Common Networking/QueryParam.swift
> +    case reactions = "t"
Yep, removed.

2022-08-11 01:50 UTC, RyanRory commented on SessionMessagingKit/Open Groups/OpenGroupManager.swift
> -                return
This is a bit tricky. I've updated the code to remain this logic only when both `message.base64EncodedData` and `message.reactions` are nil, we remove the message.

2022-08-11 05:09 UTC, mpretty-cyro commented on SessionMessagingKit/Open Groups/OpenGroupManager.swift
> -                return
No worries, I think that should be fine - I expect we'll be doing another release around the start of September where we can properly remove it again (I just wanted a little bit more time than the 1-2 weeks SOGS will have to update before Emoji Reacts gets released)

2022-08-11 05:12 UTC, mpretty-cyro requested changes

2022-08-11 05:12 UTC, mpretty-cyro commented on SessionMessagingKit/Sending & Receiving/MessageSender.swift
> +                let serverTimestampMs: UInt64? = (data.posted == nil) ? nil : UInt64(floor(data.posted! * 1000))
So you should be able to clean this up (and avoid the force-unwrap) by mapping from the nullable type:
```
let serverTimestampMs: UInt64? = data.posted.map { UInt64(floor($0 * 1000)) }
```

2022-08-11 06:04 UTC, mpretty-cyro approved these changes

2022-08-12 01:27 UTC, mpretty-cyro approved these changes

2022-08-23 02:25 UTC, merged