Add documents section for all media page
oxen-io/session-ios pull request #646
Opened 2022-07-28 23:40 UTC by RyanRory

2022-08-08 06:30 UTC, mpretty-cyro requested changes
Also found a few issues:
- [ ] Tapping on a document in the document list doesn't do anything (should have the same behaviour as within a conversation - either show the document preview UI or the share sheet)
- [ ] Tapping on media and then the `All Media` nav button animates to the tile view with no documents tab (unsure about this one - is this desired behaviour?)
- [ ] Tapping on media in the Media/Documents screen does nothing (should animate to the media detail screen with the custom transition)
- [ ] The Media/Documents screen doesn't have the "Select" nav option when on the media tab (for multi-select & local file deletion)
  - [ ] Probably want a swipe-to-delete for document files (similar to the local delete for media files?)
- [x] Looks like there are a few missing localised strings as well:
<img width="363" alt="Screen Shot 2022-08-08 at 4 43 03 pm" src="https://user-images.githubusercontent.com/15862619/183355671-faaf8dc8-f716-4ea0-b92b-0d44cd7aedbb.png">

2022-08-08 06:30 UTC, mpretty-cyro commented on Session/Media Viewing & Editing/MediaGalleryViewModel.swift
> +                        \(interaction[.threadId]) = \(threadId)
Please shift the `threadId` filter line above the `variant` and `sourceFilename` lines (we want to try filter indexed columns first before filtering on unindexed ones to minimise the performance impact)

2022-08-10 03:43 UTC, RyanRory commented
> * Probably want a swipe-to-delete for document files (similar to the local delete for media files?)

There is a conflict in swiping to left for deletion documents and change sections from documents to media. So won't go ahead with this function in this PR.

2022-08-11 05:01 UTC, mpretty-cyro approved these changes

2022-09-14 02:20 UTC, merged